#! /bin/bash

# Prerequisites: xsltproc, prince (v13)
# Usage:         ./make-pdf FILE
# Example:       ./make-pdf A\ béke\ napja\ közel.xml

# Exit immediately if a command exits with a non-zero status.
set -e

# Params
########
if [ -z "$1" ]; then
  echo "Usage: ./make-pdf FILE"
  exit 1
fi

if [ ! -f "$1" ]; then
  echo "\"$1\" doesn't exist. Enter a valid XML file."
  exit 1
fi

# Prerequisites
###############
if [ $(prince --version | grep -oP "Prince \K(\d+)") -lt 13 ] ; then
  echo "Minimum Prince version is 13. Please upgrade prince package."
  exit 1
fi

# Variables
###########
file=$1
name="$(basename "$file" .xml)"
author="Gyuris Gellért" # Author for PDF

# Running
#########
echo -n "Making \"$file\"... "

if [[ $file = *".xsl.xml" ]]; then
  # Generate PDF from XSL(HTML) version
  xsltproc "$name.xml" | prince -o "pdf/$name.pdf" --pdf-author="$author" --pdf-title="$name"  --no-warn-css-unsupported -
else
  # Generate PDF from original XML
  prince "$file" -o "pdf/$name.pdf" --pdf-author="$author" --pdf-title="$name" --no-warn-css-unsupported
fi

echo "done"
