#! /bin/bash

# Prerequisites: xsltproc, prince (v13)
# Usage:         ./make-pdf [-p EXPORTPATH] [-t TOOL] FILE
# Examples:      ./make-pdf A\ béke\ napja\ közel.xml
#                ./make-pdf -p ../song "A béke napja közel.xml"
#                ./make-pdf -p ../songs -t pagedjs "A béke napja közel.xml"

# Exit immediately if a command exits with a non-zero status.
set -e

# Prerequisites
###############
if [ $(prince --version | grep -oP "Prince \K(\d+)") -lt 13 ]; then
  echo "Minimum Prince version is 13. Please upgrade prince package."
  exit 1
fi

# Params and variables
######################
help=$(cat <<'EOT'
Usage: ./make-pdf [options] FILE
  -t    Tool for processing: prince, weasyprint, pagedjs
  -p    Path to export
EOT
)

exportpath="../export-pdf"
tool="prince"
while getopts "t:p:h" opt; do
  case ${opt} in
    t)
      tool=$OPTARG
      if ! [[ $tool =~ ^prince|weasyprint|pagedjs$ ]]; then
        echo "Supported HTML2PDF converters are: prince, weasyprint and pagedjs."
        echo "$help"
        exit 1
      fi
      ;;
    p)
      exportpath=$OPTARG
      ;;
    h)
      echo "$help"
      exit 0
      ;;
    *)
      echo "$help"
      exit 1
      ;;
  esac
done

file=${@:$OPTIND:1}
if [ -z "$file" ]; then
  echo "FILE is not specified."
  echo "$help"
  exit 1
fi
if [ ! -f "$file" ]; then
  echo "\"$1\" doesn't exist. Enter a valid XML file."
  echo "$help"
  exit 1
fi

name="$(basename "$file" .xml)"
dir="$(dirname "$file")"
author="Gyuris Gellért" # Author for PDF

# Running
#########

if [[ $file = *".xsl.xml" ]]; then
  # Generate PDF from XSL(HTML) version
  if [ $tool == "prince" ]; then
    echo -n "Making PDF [Prince]... $file... "
    cd $dir && xsltproc "$name.xml" | prince -o "$exportpath/$name.pdf" --pdf-author="$author" --pdf-title="$name"  --no-warn-css-unsupported -
    echo "done"
  elif [ $tool == "weasyprint" ]; then
    echo -n "Making PDF [WeasyPrint]... $file... "
    cd $dir && xsltproc "$name.xml" | weasyprint --quiet - "$exportpath/$name.pdf"
    echo "done"
  elif [ $tool == "pagedjs" ]; then
    echo -n "Making PDF [Paged.js]... $file... "
    cd $dir
    xsltproc "$name.xml" > "$name.html"
    pagedjs-cli -o "$exportpath/$name.pdf" "$name.html"
    rm -f "$name.html"
    cd ..
    echo "done"
  fi
else
  # Generate PDF from original XML
  if [ $tool == "prince" ]; then
    echo -n "Making PDF [Prince]... $file... "
    cd $dir && prince "$name.xml" -o "$exportpath/$name.pdf" --pdf-author="$author" --pdf-title="$name" --no-warn-css-unsupported
    echo "done"
  elif [ $tool == "weasyprint" ]; then
    echo "Weasyprint doesn't support processing XML... $file"
  elif [ $tool == "pagedjs" ]; then
    echo "Paged.js doesn't support processing XML... $file"
  fi
fi

